server:
     port: 9001 #启动端口

spring:
  application:
          name: zPluto-oauth2-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://39.106.48.25/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
      username: root
      password: root

eureka:
    client:
       serviceUrl:
              defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:1111}/eureka/

logging:
    level:
      org.springframework.security: DEBUG



