spring:
    application:
        name: zPluto-service-base
    profiles:
        active: dev

    rabbitmq:
           host: ${RABBIT_MQ_HOST:localhost}
           port:  ${RABBIT_MQ_PORT:5672}
           username: guest
           password: guest

    cloud:
           bus:
              trace:
                enabled: true

management:
       security:
            enabled: false

#zPluto-service-base
server:
    port: 8771 #启动端口

#springboot监控 actuator插件 开启全部端点权限
endpoints:
  sensitive: false

eureka:
    client:
       serviceUrl:
              defaultZone:  http://${EUREKA_HOST:localhost}:${EUREKA_PORT:1111}/eureka/


