spring:
    application:
        name: zPluto-service-base

server:
    port: 8771 #启动端口

eureka:
    client:
       serviceUrl:
              defaultZone:  http://${EUREKA_HOST:localhost}:${EUREKA_PORT:1111}/eureka/