server:
    port: 8777

spring:
    application:
        name: zPluto-bus-rabbit
    rabbitmq:
             host: ${RABBIT_MQ_HOST:localhost}
             port:  ${RABBIT_MQ_PORT:5672}
             username: guest
             password: guest