spring:
    application:
        name: zPluto-cloud-config
    cloud:
        config:
           server:
                git:
                  uri:
                  search-paths:
                  username:
                  password:

server:
    port: 8779 #启动端口
