spring:
    application:
        name: zPluto-cloud-config
    cloud:
        config:
           server:
                git:
                  uri:  https://gitee.com/zh-json/spring-cloud-config-git.git
                  search-paths:   spring-cloud-in-action/config-repo
                  username: 23862691@qq.com
                  password: zhou900914
    rabbitmq:
               host: ${RABBIT_MQ_HOST:localhost}
               port:  ${RABBIT_MQ_PORT:5672}
               username: guest
               password: guest

server:
    port: 8779 #启动端口


eureka:
    client:
       serviceUrl:
              defaultZone:  http://${EUREKA_HOST:localhost}:${EUREKA_PORT:1111}/eureka/

# http://127.0.0.1:8779/didispace/dev/master   访问 didispace应用,dev环境,master分支
# http://127.0.0.1:8779/didispace-dev.properties