spring:
    application:
        name: zPluto-api-zuul


server:
    port: 8775 #启动端口


zuul:
    retryable: false #取消重试机制
    addHostHeader: true # 解决重定向，使网关在进行路由转发前为请求设置到Host信息
    routes:
        ribbon-consumer:
                path: /api-consumer/**
                serviceId: zPluto-ribbon-consumer
                customSensitiveHeader: true  # 开启自定义默认敏感头信息


eureka:
    client:
       serviceUrl:
              defaultZone:  http://${EUREKA_HOST:localhost}:${EUREKA_PORT:1111}/eureka/



