spring:
    application:
        name: zPluto-ribbon-consumer

server:
    port: 8773 #启动端口

eureka:
    client:
       serviceUrl:
              defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:1111}/eureka/